### ISSUE TITLE
Issues with '∀'?

### ISSUE THREAD

**Issue by sjakobi** [PanAeon/vscode-language-dhall#1]
Disclaimer: I'm new to VSCode, and new to this extension.

I opened [this file](https://github.com/FormationAI/dhall-bhat/blob/923a47ae6722facc26fbaaee8a039756152d1014/Applicative/Type), but didn't get any highlighting. The highlighting works on other files.

![image](https://user-images.githubusercontent.com/3664523/62714876-a8b8e780-b9ff-11e9-8bf0-62be445c9f1f.png)

**Comment by sjakobi** [comment]
Same problem with https://github.com/FormationAI/dhall-bhat/blob/923a47ae6722facc26fbaaee8a039756152d1014/Applicative/extractFunctor, so it's probably not (only) due to `∀`.

**Comment by sjakobi** [comment]
Oops, I just forgot to set the language mode to Dhall – not sure you can do anything about that…

**Comment by sjakobi** [comment]
> not sure you can do anything about that…

Or is there a way to configure VSCode to automatically set the language mode to Dhall for files without file extension?

**Comment by PanAeon** [comment]
> Or is there a way to configure VSCode to automatically set the language mode to Dhall for files without file extension?

@sjakobi   it looks like there's no way at the moment to associate a file without an extension with a particular language(
You can associate with `dhall` all files in a particular folder, like:
```
"files.associations": {
        "**/dhall-kubernetes/**": "dhall"
    }
```
but it's got a side effect that all the other files in the folder are going to be recognized as dhall.

**Comment by sjakobi** [comment]
Thanks for the help @PanAeon! :)
